export enum ApiDienstverwendung {
  ADMINISTRATOR_IN = "Administrator/in",
  AGILE_COACH = "Agile Coach",
  ASSISTENT_IN = "Assistent/in",
  AUSBILDUNGSBEAUFTRAGTE_R = "Ausbildungsbeauftragte/in",
  DEMAND_MANAGER_IN = "Demand Manager/in",
  DEVELOPER = "Developer",
  ENTERPRISE_ARCHITEKT_IN = "Enterprise Architekt/in",
  HAUSTECHNIKER_IN = "Haustechniker/in",
  INFRASTRUKTUR_ARCHITEKT_IN = "Infrastruktur Architekt/in",
  IT_ANALYST_IN = "IT-Analyst/in",
  IT_CONSULTANT = "IT-Consultant",
  IT_MANAGER_IN = "IT-Manager/in",
  IT_SUPPORT = "IT-Support",
  NETZWERKADMINISTRATOR_IN = "Netzwerkadministrator/in",
  PORTIERFUNKTION = "Platform Engineer",
  PRODUCT_OWNER = "Product Owner",
  PROJEKTLEITER_IN = "Projektleiter/in",
  PROJEKTMANAGER_IN = "Projektmanager/in",
  SERVICEMANAGER_IN = "Servicemanager/in",
  SOFTWARE_ARCHITEKT_IN = "Software Architekt/in",
  SOFTWARE_DEVELOPER_IN = "Software Developer/in",
  SYSTEMADMINISTRATOR_IN = "Systemadministrator/in",
  TEST_ARCHITEKT_IN = "Test Architekt/in",
  TEST_ENGINEER = "Test Engineer",
  TEST_MANAGER_IN = "Test Manager/in",
  ZIVILDIENSTLEISTENDER = "Zivildienstleistender",
  ARBEITSVORBEREITUNG_OPERATOR = "Arbeitsvorbereitung-Operator",
  OPERATOR = "Operator",
  CHEFOPERATOR = "Chefoperator",
  OPERATOR_IN_AUSBILDUNG = "Operator in Ausbildung",
  RICHTFUNKTION_F_D_BEDIENSTETENGRUPPE_2 = "Richtfunktion f.d. Bedienstetengruppe 2",
  REQUIREMENTS_ENGINEER = "Requirements Engineer",
}

export function getApiDienstverwendungDisplayValues(): { key: ApiDienstverwendung, value: string }[] {
  return [
    { key: ApiDienstverwendung.ADMINISTRATOR_IN, value: "Administrator/in" },
    { key: ApiDienstverwendung.AGILE_COACH, value: "Agile Coach" },
    { key: ApiDienstverwendung.ASSISTENT_IN, value: "Assistent/in" },
    { key: ApiDienstverwendung.AUSBILDUNGSBEAUFTRAGTE_R, value: "Ausbildungsbeauftragte/in" },
    { key: ApiDienstverwendung.DEMAND_MANAGER_IN, value: "Demand Manager/in" },
    { key: ApiDienstverwendung.DEVELOPER, value: "Developer" },
    { key: ApiDienstverwendung.ENTERPRISE_ARCHITEKT_IN, value: "Enterprise Architekt/in" },
    { key: ApiDienstverwendung.HAUSTECHNIKER_IN, value: "Haustechniker/in" },
    { key: ApiDienstverwendung.INFRASTRUKTUR_ARCHITEKT_IN, value: "Infrastruktur Architekt/in" },
    { key: ApiDienstverwendung.IT_ANALYST_IN, value: "IT-Analyst/in" },
    { key: ApiDienstverwendung.IT_CONSULTANT, value: "IT-Consultant" },
    { key: ApiDienstverwendung.IT_MANAGER_IN, value: "IT-Manager/in" },
    { key: ApiDienstverwendung.IT_SUPPORT, value: "IT-Support" },
    { key: ApiDienstverwendung.NETZWERKADMINISTRATOR_IN, value: "Netzwerkadministrator/in" },
    { key: ApiDienstverwendung.PORTIERFUNKTION, value: "Platform Engineer" },
    { key: ApiDienstverwendung.PRODUCT_OWNER, value: "Product Owner" },
    { key: ApiDienstverwendung.PROJEKTLEITER_IN, value: "Projektleiter/in" },
    { key: ApiDienstverwendung.PROJEKTMANAGER_IN, value: "Projektmanager/in" },
    { key: ApiDienstverwendung.SERVICEMANAGER_IN, value: "Servicemanager/in" },
    { key: ApiDienstverwendung.SOFTWARE_ARCHITEKT_IN, value: "Software Architekt/in" },
    { key: ApiDienstverwendung.SOFTWARE_DEVELOPER_IN, value: "Software Developer/in" },
    { key: ApiDienstverwendung.SYSTEMADMINISTRATOR_IN, value: "Systemadministrator/in" },
    { key: ApiDienstverwendung.TEST_ARCHITEKT_IN, value: "Test Architekt/in" },
    { key: ApiDienstverwendung.TEST_ENGINEER, value: "Test Engineer" },
    { key: ApiDienstverwendung.TEST_MANAGER_IN, value: "Test Manager/in" },
    { key: ApiDienstverwendung.ZIVILDIENSTLEISTENDER, value: "Zivildienstleistender" },
    { key: ApiDienstverwendung.ARBEITSVORBEREITUNG_OPERATOR, value: "Arbeitsvorbereitung-Operator" },
    { key: ApiDienstverwendung.OPERATOR, value: "Operator" },
    { key: ApiDienstverwendung.CHEFOPERATOR, value: "Chefoperator" },
    { key: ApiDienstverwendung.OPERATOR_IN_AUSBILDUNG, value: "Operator in Ausbildung" },
    { key: ApiDienstverwendung.RICHTFUNKTION_F_D_BEDIENSTETENGRUPPE_2, value: "Richtfunktion f.d. Bedienstetengruppe 2" },
    { key: ApiDienstverwendung.REQUIREMENTS_ENGINEER, value: "Requirements Engineer" },
  ];
}
