export enum ApiTaetigkeitTyp {
  ANALYSE = "Analyse",
  ANFRAGEBEANTWORTUNG = "Anfragebeantwortung",
  BENUTZERBETREUUNG = "Benutzerbetreuung",
  DATENBANKADMINISTRATION = "Datenbankadministration",
  DATENBANKDESIGN = "Datenbankdesign",
  KONZEPTION = "Konzeption",
  NETZWERKADMINISTRATION = "Netzwerkadministration",
  ORGANISATION = "Organisation",
  PROGRAMMIERUNG = "Programmierung",
  QUALITAETSSICHERUNG = "Qualit\u00e4tssicherung",
  SCHULUNG = "Schulung",
  SOFTWAREDESIGN = "Softwaredesign",
  STATISTIK = "Statistik",
  SYSTEMADMINISTRATION = "Systemadministration",
  VERARBEITUNG_REORG = "Verarbeitung-Reorg",
  WEITERBILDUNG = "Weiterbildung",
  WORKSHOP = "Workshop",
  BERICHT = "Bericht",
  BESPRECHUNG = "Besprechung",
  DOKUMENTATION = "Dokumentation",
  RECHERCHE = "Recherche",
  REISETAETIGKEIT = "Reiset\u00e4tigkeit",
  ADMINISTRATIVES = "Administratives",
  KONFERENZ = "Konferenz",
  PROJEKTMANAGEMENT = "Projektmanagement",
  FEHLERBEHEBUNG = "Fehlerbehebung",
  WARTUNG = "Wartung",
  TEST = "Test",
  PRODUKTIONSUEBERNAHME = "Produktions\u00fcbernahme",
  BEREITSCHAFT = "Bereitschaft",
  DEPLOYMENT = "Deployment",
}

export function getApiTaetigkeitTypDisplayValues(): { key: ApiTaetigkeitTyp, value: string }[] {
  return [
    { key: ApiTaetigkeitTyp.ANALYSE, value: "Analyse" },
    { key: ApiTaetigkeitTyp.ANFRAGEBEANTWORTUNG, value: "Anfragebeantwortung" },
    { key: ApiTaetigkeitTyp.BENUTZERBETREUUNG, value: "Benutzerbetreuung" },
    { key: ApiTaetigkeitTyp.DATENBANKADMINISTRATION, value: "Datenbankadministration" },
    { key: ApiTaetigkeitTyp.DATENBANKDESIGN, value: "Datenbankdesign" },
    { key: ApiTaetigkeitTyp.KONZEPTION, value: "Konzeption" },
    { key: ApiTaetigkeitTyp.NETZWERKADMINISTRATION, value: "Netzwerkadministration" },
    { key: ApiTaetigkeitTyp.ORGANISATION, value: "Organisation" },
    { key: ApiTaetigkeitTyp.PROGRAMMIERUNG, value: "Programmierung" },
    { key: ApiTaetigkeitTyp.QUALITAETSSICHERUNG, value: "Qualit\u00e4tssicherung" },
    { key: ApiTaetigkeitTyp.SCHULUNG, value: "Schulung" },
    { key: ApiTaetigkeitTyp.SOFTWAREDESIGN, value: "Softwaredesign" },
    { key: ApiTaetigkeitTyp.STATISTIK, value: "Statistik" },
    { key: ApiTaetigkeitTyp.SYSTEMADMINISTRATION, value: "Systemadministration" },
    { key: ApiTaetigkeitTyp.VERARBEITUNG_REORG, value: "Verarbeitung-Reorg" },
    { key: ApiTaetigkeitTyp.WEITERBILDUNG, value: "Weiterbildung" },
    { key: ApiTaetigkeitTyp.WORKSHOP, value: "Workshop" },
    { key: ApiTaetigkeitTyp.BERICHT, value: "Bericht" },
    { key: ApiTaetigkeitTyp.BESPRECHUNG, value: "Besprechung" },
    { key: ApiTaetigkeitTyp.DOKUMENTATION, value: "Dokumentation" },
    { key: ApiTaetigkeitTyp.RECHERCHE, value: "Recherche" },
    { key: ApiTaetigkeitTyp.REISETAETIGKEIT, value: "Reiset\u00e4tigkeit" },
    { key: ApiTaetigkeitTyp.ADMINISTRATIVES, value: "Administratives" },
    { key: ApiTaetigkeitTyp.KONFERENZ, value: "Konferenz" },
    { key: ApiTaetigkeitTyp.PROJEKTMANAGEMENT, value: "Projektmanagement" },
    { key: ApiTaetigkeitTyp.FEHLERBEHEBUNG, value: "Fehlerbehebung" },
    { key: ApiTaetigkeitTyp.WARTUNG, value: "Wartung" },
    { key: ApiTaetigkeitTyp.TEST, value: "Test" },
    { key: ApiTaetigkeitTyp.PRODUKTIONSUEBERNAHME, value: "Produktions\u00fcbernahme" },
    { key: ApiTaetigkeitTyp.BEREITSCHAFT, value: "Bereitschaft" },
    { key: ApiTaetigkeitTyp.DEPLOYMENT, value: "Deployment" },
  ];
}
